### Get currency exchange 8000
GET {{host-8000}}/currency-exchange/from/USD/to/INR

### Get currency exchange 8001
GET {{host-8001}}/currency-exchange/from/EUR/to/INR

### Get currency exchange k8s
GET {{host-k8s}}/currency-exchange/from/USD/to/INR
